---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jjsiv.io
  resources:
  - fluentbits
  - loggingpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jjsiv.io
  resources:
  - fluentbits/finalizers
  - loggingpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - jjsiv.io
  resources:
  - fluentbits/status
  - loggingpipelines/status
  verbs:
  - get
  - patch
  - update
