apiVersion: jjsiv.io/v1alpha1
kind: FluentBit
metadata:
  labels:
    app.kubernetes.io/name: logging-operator
    app.kubernetes.io/managed-by: kustomize
  name: fluentbit-sample
spec:
  # TODO(user): Add fields here
