apiVersion: jjsiv.io/v1alpha1
kind: LoggingPipeline
metadata:
  labels:
    app.kubernetes.io/name: logging-operator
    app.kubernetes.io/managed-by: kustomize
    pipeline/enabled: "true"
  name: loggingpipeline-sample
spec:
  inputs:
    tail: {}
  outputs:
    stdout: {}
