apiVersion: jjsiv.io/v1alpha1
kind: FluentBit
metadata:
  labels:
    app.kubernetes.io/name: logging-operator
    app.kubernetes.io/managed-by: kustomize
  name: fluentbit-sample
spec:
  image: docker.io/fluent/fluent-bit:4.2.0
  pipelineSelector:
    matchLabels:
      pipeline/enabled: "true"
